name: Pull request merging master into bot-updates
on:
  workflow_dispatch:
jobs:
  bot-updatesPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: bot-updates
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: bot-updates-promotion
